In [1]:
import unidecode
import string
import random
import re
import time
import math
import torch

from torch.autograd import Variable

In [2]:
CHUNK_LEN = 200
TRAIN_PATH = '../data/dickens_train.txt'

def load_dataset(path):
    all_characters = string.printable
    n_characters = len(all_characters)

    file = unidecode.unidecode(open(path, 'r').read())
    return file

In [3]:
data = load_dataset(TRAIN_PATH)

In [4]:
len(data)

1136673

In [5]:
data[0:5]

'DAVID'

In [6]:
data[2032]

'a'

In [7]:
def random_chunk():
    file = load_dataset(TRAIN_PATH)
    start_index = random.randint(0, len(file) - CHUNK_LEN - 1)
    end_index = start_index + CHUNK_LEN + 1
    return file[start_index:end_index]

In [8]:
data_chunk = random_chunk()

In [9]:
print(data_chunk)

hing further to say, 
sir, except that I hope you will bear with me and make allowance 
for me.'

'Of that, Mr. Neville, you may be sure,' returned the Minor Canon.  
'I don't preach more than I can he


In [10]:
all_characters = string.printable

In [11]:
all_characters

'0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~ \t\n\r\x0b\x0c'

In [12]:
torch.zeros(len(data_chunk)).long()

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
all_characters.index("C")

38

In [14]:
def char_tensor(strings):
    all_characters = string.printable
    tensor = torch.zeros(len(strings)).long()
    for index,char in enumerate(strings):
        tensor[index] = all_characters.index(char)
    return Variable(tensor)

In [15]:
char_tensor(data_chunk)

tensor([17, 18, 23, 16, 94, 15, 30, 27, 29, 17, 14, 27, 94, 29, 24, 94, 28, 10,
        34, 73, 94, 96, 28, 18, 27, 73, 94, 14, 33, 12, 14, 25, 29, 94, 29, 17,
        10, 29, 94, 44, 94, 17, 24, 25, 14, 94, 34, 24, 30, 94, 32, 18, 21, 21,
        94, 11, 14, 10, 27, 94, 32, 18, 29, 17, 94, 22, 14, 94, 10, 23, 13, 94,
        22, 10, 20, 14, 94, 10, 21, 21, 24, 32, 10, 23, 12, 14, 94, 96, 15, 24,
        27, 94, 22, 14, 75, 68, 96, 96, 68, 50, 15, 94, 29, 17, 10, 29, 73, 94,
        48, 27, 75, 94, 49, 14, 31, 18, 21, 21, 14, 73, 94, 34, 24, 30, 94, 22,
        10, 34, 94, 11, 14, 94, 28, 30, 27, 14, 73, 68, 94, 27, 14, 29, 30, 27,
        23, 14, 13, 94, 29, 17, 14, 94, 48, 18, 23, 24, 27, 94, 38, 10, 23, 24,
        23, 75, 94, 94, 96, 68, 44, 94, 13, 24, 23, 68, 29, 94, 25, 27, 14, 10,
        12, 17, 94, 22, 24, 27, 14, 94, 29, 17, 10, 23, 94, 44, 94, 12, 10, 23,
        94, 17, 14])

In [16]:
def random_training_set():
    chunk = random_chunk()
    inp = char_tensor(chunk[:-1])
    target = char_tensor(chunk[1:])
    return inp, target

In [17]:
input,target = random_training_set()

In [18]:
input

tensor([14, 25, 94, 17, 18, 22, 94, 24, 30, 29, 73, 94, 10, 23, 13, 94, 29, 17,
        14, 96, 12, 14, 27, 29, 10, 18, 23, 29, 34, 94, 32, 18, 29, 17, 94, 32,
        17, 18, 12, 17, 94, 17, 14, 94, 12, 10, 22, 14, 94, 18, 23, 73, 94, 10,
        23, 13, 94, 29, 30, 22, 11, 21, 14, 13, 94, 29, 17, 14, 94, 48, 14, 22,
        24, 27, 18, 10, 21, 94, 24, 30, 29, 94, 24, 15, 96, 10, 21, 21, 94, 28,
        17, 10, 25, 14, 73, 94, 22, 10, 13, 14, 94, 10, 94, 13, 14, 14, 25, 94,
        18, 22, 25, 27, 14, 28, 28, 18, 24, 23, 94, 24, 23, 94, 22, 14, 75, 94,
        94, 58, 17, 10, 29, 94, 48, 27, 75, 94, 39, 18, 12, 20, 94, 28, 30, 25,
        25, 24, 28, 14, 13, 96, 32, 24, 30, 21, 13, 94, 12, 24, 22, 14, 94, 24,
        15, 94, 29, 17, 14, 94, 48, 14, 22, 24, 27, 18, 10, 21, 73, 94, 18, 15,
        94, 18, 29, 94, 32, 14, 27, 14, 94, 12, 24, 22, 25, 21, 14, 29, 14, 13,
        78, 94])

In [19]:
target

tensor([25, 94, 17, 18, 22, 94, 24, 30, 29, 73, 94, 10, 23, 13, 94, 29, 17, 14,
        96, 12, 14, 27, 29, 10, 18, 23, 29, 34, 94, 32, 18, 29, 17, 94, 32, 17,
        18, 12, 17, 94, 17, 14, 94, 12, 10, 22, 14, 94, 18, 23, 73, 94, 10, 23,
        13, 94, 29, 30, 22, 11, 21, 14, 13, 94, 29, 17, 14, 94, 48, 14, 22, 24,
        27, 18, 10, 21, 94, 24, 30, 29, 94, 24, 15, 96, 10, 21, 21, 94, 28, 17,
        10, 25, 14, 73, 94, 22, 10, 13, 14, 94, 10, 94, 13, 14, 14, 25, 94, 18,
        22, 25, 27, 14, 28, 28, 18, 24, 23, 94, 24, 23, 94, 22, 14, 75, 94, 94,
        58, 17, 10, 29, 94, 48, 27, 75, 94, 39, 18, 12, 20, 94, 28, 30, 25, 25,
        24, 28, 14, 13, 96, 32, 24, 30, 21, 13, 94, 12, 24, 22, 14, 94, 24, 15,
        94, 29, 17, 14, 94, 48, 14, 22, 24, 27, 18, 10, 21, 73, 94, 18, 15, 94,
        18, 29, 94, 32, 14, 27, 14, 94, 12, 24, 22, 25, 21, 14, 29, 14, 13, 78,
        94, 32])

In [22]:
input.type()

'torch.LongTensor'